### ISSUE TITLE
photos not found

### ISSUE THREAD

**Issue by shieldsa13** [shieldsa13/Book-Of-Fate#2]
The photos point to an incorrect address. Must change in source code

**Comment by Fishkeeper94** [comment]
Line 5 of geomancy.es6.js is defined 
/Users/mogihara/Documents/Projects/BookOfFate/newScans/framed
Change all constant domains

**Comment by shieldsa13** [comment]
Thanks Dylan. It needed to be changed in bundle also. It's working now if you use the base dir as webroot.
